# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(562, 550)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 392, 234))
        self.calendarWidget.setNavigationBarVisible(False)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(400, 10, 160, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stop_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.stop_btn.setObjectName("stop_btn")
        self.verticalLayout.addWidget(self.stop_btn)
        self.start_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.start_btn.setObjectName("start_btn")
        self.verticalLayout.addWidget(self.start_btn)
        self.auto_play_box = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.auto_play_box.setObjectName("auto_play_box")
        self.verticalLayout.addWidget(self.auto_play_box)
        self.video_widget = QVideoWidget(parent=self.centralwidget)
        self.video_widget.setGeometry(QtCore.QRect(9, 249, 541, 251))
        self.video_widget.setObjectName("video_widget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 562, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.auto_play_box.setText(_translate("MainWindow", "auto_play_box"))
from PyQt6.QtMultimediaWidgets import QVideoWidget
